version: 2.1

jobs:
  publish:
    machine:
      image: ubuntu-2204:2022.10.2
    steps:
      - add_ssh_keys:
          fingerprints:
            - "59:58:9f:ef:2c:5d:54:26:d3:2b:c8:37:88:97:9c:36"
      - checkout
      - run: git config --global user.name "CircleCI Deployer"
      - run: wget https://github.com/babashka/babashka/releases/download/v1.0.168/babashka-1.0.168-linux-amd64-static.tar.gz
      - run: tar -xf babashka*
      - run: rm babashka*
      - run: mv bb /tmp
      - run: /tmp/bb scripts/prepare-ring-release.clj generic-lsp
      - run: /tmp/bb scripts/prepare-ring-release.clj star-linter
      - run: /tmp/bb scripts/prepare-ring-release.clj minivac

workflows:
  version: 2
  default-workflow:
    jobs:
      - publish:
          # requires:
          #   - test
          filters:
            branches:
              only: master
